### ISSUE TITLE
Can't fine lottie animations in APK

### ISSUE THREAD

**Issue by dnestico** [nielsrowinbik/google-home-assistant#278]
Hey, its me again haha...

So I got the google home apk downloaded, but where exactly do I find the animations? pls help

<img width="741" alt="Screen Shot 2022-06-07 at 2 57 53 PM" src="https://user-images.githubusercontent.com/3034555/172460990-65ff5cde-b8d4-4125-ad7b-f1038c45fed2.png">

**Comment by nielsrowinbik** [comment]
I'm sorry, I don't remember where exactly. I believe they're `.json` files, and I vaguely remember them being inside the `res` folder somewhere. Have a look around. Just be aware that they may not be in there anymore at all. At some point in time I stopped being able to find newly added animations, so they probably moved to a different animation library or started bundling the animations differently. If you can't find the animations I think you're still able to use just raw images, which you can get by screenshotting the actual Google Home app. I don't think I'll be able to help you much further, so I'll be closing this.
